version: '3.8'

services:
  db:
    image: postgres:12.14
    container_name: wallet-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1111
    networks:
      - wallet-network

  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-service
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1111
    depends_on:
      - db
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge



